Development
solufemi91/sparta-project1-jsgame pull request #1
Opened 2017-11-07 22:56 UTC by solufemi91

This is Steven's work for the first sprint

2017-11-07 23:25 UTC, JSChilds commented on main.js
> +        alert("Cool, carm and collected. You scored!");
This needs to be indented.

2017-11-07 23:26 UTC, JSChilds commented on test.html
> +<!DOCTYPE html>
Remove this file from the file system if it's not being used.

2017-11-07 23:28 UTC, JSChilds requested changes
Make the changes highlighted in the comments. It also seems like the keeper can't actually save the goal, in which case there is no real challenge.

2017-11-08 10:07 UTC, JSChilds approved these changes

2017-11-09 22:30 UTC, j-mcgregor requested changes
You need to remove the alert() functions in the code.

2017-11-10 10:03 UTC, j-mcgregor approved these changes
Very nice, well done

2017-11-10 10:03 UTC, j-mcgregor approved these changes

2017-11-10 10:10 UTC, richgurney requested changes
There is a bug with the game when you score the keeper gets a point. Also you will need to rearrange the home page because at the moment the index.html will be loaded first and the home.html will not be seen.

2017-11-10 12:22 UTC, richgurney approved these changes

2018-01-26 12:00 UTC, merged